### ISSUE TITLE
Mathjax not rendering

### ISSUE THREAD

**Issue by lcolladotor** [jbryer/Rgitbook#1]
At http://jason.bryer.org/Rgitbook/building/building.html the math is not rendering as show below:

![screen shot 2014-04-22 at 2 36 06 pm](https://cloud.githubusercontent.com/assets/2288213/2769083/16220e3a-ca4d-11e3-9671-ea35955c2b06.png)

**Comment by jbryer** [comment]
Please try again, it is rendering fine on my Mac with Google Chrome.

**Comment by lcolladotor** [comment]
It works now =)

I'm also using Google Chrome Version 34.0.1847.116 on my Mac with OS 10.8.5.

**Comment by jbryer** [comment]
Great! Thanks
