### ISSUE TITLE
Use of pandoc for citations

### ISSUE THREAD

**Issue by kylelundstedt** [jbryer/Rgitbook#13]
Rgitbook is a terrific idea; looking forward to putting it to use.  Just one suggestion - many folks, including the Rstudio team, are moving to a pandoc-driven workflow.  So, while the knitcitations package looks cool, you might be well served to allow pandoc-based citations as well.  Just my two cents; thanks!

**Comment by maxheld83** [comment]
+1

**Comment by dpastoor** [comment]
unfortunately I think this project is dead :-(

**Comment by maxheld83** [comment]
yeah, looks like it – though it would be a dream!
