### ISSUE TITLE
checkForGitboook(): Cannot find node.js.

### ISSUE THREAD

**Issue by grovesjosephn** [jbryer/Rgitbook#23]
i have node installed and its not getting detected!

which npm:
/usr/local/bin/npm

> checkForGitbook()
> Error in checkForGitbook() : 
>   Cannot find node.js. You can install it from http://nodejs.org/download/

**Comment by renkun-ken** [comment]
I update node.js to 0.10.29 and Rgitbook no longer works with the same error. Here is the output.

``` rconsole
> Rgitbook::checkForGitbook()

Usage: npm <command>

where <command> is one of:
    add-user, adduser, apihelp, author, bin, bugs, c, cache,
    completion, config, ddp, dedupe, deprecate, docs, edit,
    explore, faq, find, find-dupes, get, help, help-search,
    home, i, info, init, install, isntall, issues, la, link,
    list, ll, ln, login, ls, outdated, owner, pack, prefix,
    prune, publish, r, rb, rebuild, remove, repo, restart, rm,
    root, run-script, s, se, search, set, show, shrinkwrap,
    star, stars, start, stop, submodule, t, tag, test, tst, un,
    uninstall, unlink, unpublish, unstar, up, update, v,
    version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Kun\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@1.4.14 C:\PROGRA~1\nodejs\node_modules\npm
Error in Rgitbook::checkForGitbook() : 
  Cannot find node.js. You can install it from http://nodejs.org/download/
In addition: Warning message:
running command 'npm' had status 1 
```

**Comment by Robinlovelace** [comment]
Same problem here

**Comment by renkun-ken** [comment]
@Robinlovelace, my fork solves the problem: https://github.com/renkun-ken/Rgitbook.

**Comment by Robinlovelace** [comment]
Yes, true - using your fork. There are other problems with this project so
I'm trying this today: https://github.com/hadley/bookdown

**Comment by kbenoit** [comment]
@renkun-ken, thanks for the fork, that worked for me. Tests showed that:
Mac OS X: 

``` r
> t1 <- try(system("npm", ignore.stdout=TRUE))
> t1
[1] 1
> t2 <- try(system("npm version", intern = FALSE, ignore.stdout=TRUE))
> t2
[1] 0
```

but on Linux:

``` r
> t1 <- try(system("npm", ignore.stdout=TRUE))
> t1
[1] 0
```

Who knows why this is happening. But adding the `version` solves it.

**Comment by paternogbc** [comment]
I am having the same problem on linux (Ubuntu 14.04):

> require(Rgitbook)
> Carregando pacotes exigidos: Rgitbook
> installGitbook()
> sudo: nenhum programa de askpass especificado, tente definir SUDO_ASKPASS
> Error in installGitbook() : 
>   gitbook installation failed. Typically installing as root/Administrator from the terminal/console works:
>    npm install gitbook -g
>    npm install gitbook-pdf -g
>    npm install gitbook-plugin

The commands below seems not to work:
   npm install gitbook -g
   npm install gitbook-pdf -g
   npm install gitbook-plugin

Error in checkForGitbook() : 
  Cannot find node.js. You can install it from http://nodejs.org/download/

Any help?

**Comment by eduardszoecs** [comment]
On Ubuntu 14.04 this helped for me:

```
sudo npm uninstall -g gitbook
sudo npm install -g gitbook-cli
```

**Comment by Djaiff** [comment]
This worked for me : 
```
- sudo npm uninstall -g gitbook
- sudo npm install -g gitbook-cli
```
Then use the fork of @renkun-ken
