### ISSUE TITLE
Doesn't detect the node.js installed

### ISSUE THREAD

**Issue by janeshdev** [jbryer/Rgitbook#4]
Hi, I am trying to follow your instructions to implement gitbook using R. I installed your package and I installed `node.js` from http://nodejs.org/ . I then installed gitbook using node.js command prompt and it shows the program is installed. However, when I check using the commands on your tutorials I get the following errors: 

``` r
> installGitbook()
Error in installGitbook() : 
  gitbook installation failed. Typically installing as root/Administrator from the terminal/console works:
   npm install gitbook -g
   npm install gitbook-pdf -g
> checkForGitbook()
Error in checkForGitbook() : 
  Cannot find node.js. You can install it from http://nodejs.org/download/
> gitbookInfo()
Error in checkForGitbook(quiet = TRUE) : 
  Cannot find node.js. You can install it from http://nodejs.org/download/
```

Would you please help me to eliminate this error.

**Comment by jbryer** [comment]
What operating system are you on? If on Mac or Linux, what happens when you type:

```
which npm
```

In the console? Once npm is found, you can also install gitbook using the following:

```
sudo npm install gitbook -g
sudo npm install gitbook-plugin
```

Note that I think you need to be in your project directory for it to work. It seems to create a node_modules folder for your project.

**Comment by janeshdev** [comment]
I was using windows operating system. Yesterday, it didn't work but today it seems to detect node installed. May be after the system shut down it started detecting. I am not sure what caused that problem. Thanks for your reply and this good package.

**Comment by roobyz** [comment]
Thank you @jbryer for your lovely work.  I'm on Linux and had the same problem.  It appears that [Issue #19](https://github.com/jbryer/Rgitbook/issues/19) raised the same problem as well.  @raulossada generated a solution ([pull request #22](https://github.com/jbryer/Rgitbook/pull/22/files?diff=split)), which definitely solved the issue for me.
