### ISSUE TITLE
compatibility with knitr and rstudio

### ISSUE THREAD

**Issue by stevepowell99** [jbryer/Rgitbook#6]
using knitr 1.5 and rstudio 0.98.801 as well as Rgitbook. Want to use Rgitbook because I have a long project which is overloading R (or Rstudio, not sure) when running my code from a single file. I was hoping I could use knitr and Rgitbook in parallel, so when e.g. knitr had cached some images, Rgitbook could make use of them, and vice versa. But knitr saves its stuff in e.g. file_namefiles/ whereas Rgitbook uses figure/ which I think is what knitr used to do.

Is this by design, or ...?

**Comment by jbryer** [comment]
I changed the default knitr options to be more consistent with what the gitbook.io folks were doing. You can simply change the options at the top of each Rmd file. In a future update the default knitr block will be a system option.
