### ISSUE TITLE
installGitbook() not found

### ISSUE THREAD

**Issue by pcsnow** [jbryer/Rgitbook#7]
![gitbook](https://cloud.githubusercontent.com/assets/289188/2809816/03e2799e-cd86-11e3-9068-51dd6097607e.jpg)

**Comment by pcsnow** [comment]
Ah, the next trouble posted showed me what I needed
library(Rgitbook)

Could you add that as the second step of 
http://jason.bryer.org/Rgitbook/installation/installation.html

Thanks

**Comment by jbryer** [comment]
I added the `require(Rgitbook)` to the documentation.

**Comment by pcsnow** [comment]
thanks, please close
