### ISSUE TITLE
change width of code blocks in html output?

### ISSUE THREAD

**Issue by wabarr** [jbryer/Rgitbook#9]
The default width of code blocks is a little narrow for my taste, as relatively short lines spill over onto two lines (see example screenshot below).  Is there a way to change this setting when using `buildGitbook()`?  Your package is amazing, by the way.  Thanks for your efforts (and the gitbook folks, as well)

![screen shot 2014-04-29 at 11 15 22 am](https://cloud.githubusercontent.com/assets/1576408/2831472/7eced8fc-cfb9-11e3-8bc1-e3868d9db0b5.png)

**Comment by jbryer** [comment]
@wabarr Thanks, glad you like the package. I believe you can change this using a knitr option. Take a look at the Code Decorations section on this page: http://yihui.name/knitr/options

**Comment by wabarr** [comment]
@jbryer I found the knitr option, which does change how the html file gets created when I preview it in Rstudio, but these changes are overridden by the CSS styles when the gitbook is viewed.  The width of the `<section class='normal'>` element governs how wide the column in the rendered book is, and the R code just gets line-wrapped to fit this width.  This is a serious problem for usability for me, because relatively short lines of R code are illegible when rendered.  I am not too familiar with gitbook options.  Is there a way to change these type of style parameters programmatically?
